project "assimp"
    kind "StaticLib"
    language "C++"
    cppdialect "C++17"
    staticruntime "on"

    targetdir("bin/" ..outputdir.. "/%{prj.name}")
    objdir("bin-int/" ..outputdir.. "/%{prj.name}")

    files
    {
        "include/**.h",
        "include/**.h.in",
        "include/**.inl",
        "code/**.h",
        "code/**.cpp"
    }

    removefiles {
        "code/AssetLib/IFC/IFCReaderGen_4.cpp",
        "code/AssetLib/IFC/IFCReaderGen_4.h",
        "code/Common/Version.cpp"
    }

    includedirs
    {
        "include",
        "code",
        "contrib",
        "contrib/pugixml/src",
        "contrib/openddlparser/include",
        "contrib/rapidjson/include",
        "contrib/unzip",
        "contrib/zlib",
        "%{prj.location}"
    }

    defines
    {
        "WIN32",
        "_WINDOWS",
        "ASSIMP_BUILD_DLL_EXPORT",
        "WIN32_LEAN_AND_MEAN",
        "UNICODE",
        "_UNICODE",
        "ASSIMP_BUILD_NO_OWN_ZLIB",
        "MINIZ_USE_UNALIGNED_LOADS_AND_STORES=0",
        "ASSIMP_IMPORTER_GLTF_USE_OPEN3DGC=1",
        "RAPIDJSON_HAS_STDSTRING=1",
        "RAPIDJSON_NOMEMBERITERATORCLASS",
        "_SCL_SECURE_NO_WARNINGS",
        "_CRT_SECURE_NO_WARNINGS",
        "OPENDDLPARSER_BUILD",
        "assimp_EXPORTS",
		"ASSIMP_BUILD_NO_X_IMPORTER",
		"ASSIMP_BUILD_NO_3DS_IMPORTER",
		"ASSIMP_BUILD_NO_MD3_IMPORTER",
		"ASSIMP_BUILD_NO_MDL_IMPORTER",
		"ASSIMP_BUILD_NO_MD2_IMPORTER",
		-- "ASSIMP_BUILD_NO_PLY_IMPORTER",
		"ASSIMP_BUILD_NO_ASE_IMPORTER",
		-- "ASSIMP_BUILD_NO_OBJ_IMPORTER",
		"ASSIMP_BUILD_NO_AMF_IMPORTER",
		"ASSIMP_BUILD_NO_HMP_IMPORTER",
		"ASSIMP_BUILD_NO_SMD_IMPORTER",
		"ASSIMP_BUILD_NO_MDC_IMPORTER",
		"ASSIMP_BUILD_NO_MD5_IMPORTER",
		"ASSIMP_BUILD_NO_STL_IMPORTER",
		"ASSIMP_BUILD_NO_LWO_IMPORTER",
		"ASSIMP_BUILD_NO_DXF_IMPORTER",
		"ASSIMP_BUILD_NO_NFF_IMPORTER",
		"ASSIMP_BUILD_NO_RAW_IMPORTER",
		"ASSIMP_BUILD_NO_OFF_IMPORTER",
		"ASSIMP_BUILD_NO_AC_IMPORTER",
		"ASSIMP_BUILD_NO_BVH_IMPORTER",
		"ASSIMP_BUILD_NO_IRRMESH_IMPORTER",
		"ASSIMP_BUILD_NO_IRR_IMPORTER",
		"ASSIMP_BUILD_NO_Q3D_IMPORTER",
		"ASSIMP_BUILD_NO_B3D_IMPORTER",
		-- "ASSIMP_BUILD_NO_COLLADA_IMPORTER",
		"ASSIMP_BUILD_NO_TERRAGEN_IMPORTER",
		"ASSIMP_BUILD_NO_CSM_IMPORTER",
		"ASSIMP_BUILD_NO_3D_IMPORTER",
		"ASSIMP_BUILD_NO_LWS_IMPORTER",
		"ASSIMP_BUILD_NO_OGRE_IMPORTER",
		"ASSIMP_BUILD_NO_OPENGEX_IMPORTER",
		"ASSIMP_BUILD_NO_MS3D_IMPORTER",
		"ASSIMP_BUILD_NO_COB_IMPORTER",
		"ASSIMP_BUILD_NO_BLEND_IMPORTER",
		"ASSIMP_BUILD_NO_Q3BSP_IMPORTER",
		"ASSIMP_BUILD_NO_NDO_IMPORTER",
		"ASSIMP_BUILD_NO_IFC_IMPORTER",
		"ASSIMP_BUILD_NO_XGL_IMPORTER",
		"ASSIMP_BUILD_NO_FBX_IMPORTER",
		"ASSIMP_BUILD_NO_ASSBIN_IMPORTER",
		-- "ASSIMP_BUILD_NO_GLTF_IMPORTER",
		"ASSIMP_BUILD_NO_C4D_IMPORTER",
		"ASSIMP_BUILD_NO_3MF_IMPORTER",
		"ASSIMP_BUILD_NO_X3D_IMPORTER",
		"ASSIMP_BUILD_NO_MMD_IMPORTER",
		"ASSIMP_BUILD_NO_X_EXPORTER",
		"ASSIMP_BUILD_NO_3DS_EXPORTER",
		"ASSIMP_BUILD_NO_MD3_EXPORTER",
		"ASSIMP_BUILD_NO_MDL_EXPORTER",
		"ASSIMP_BUILD_NO_MD2_EXPORTER",
		-- "ASSIMP_BUILD_NO_PLY_EXPORTER",
		"ASSIMP_BUILD_NO_ASE_EXPORTER",
		-- "ASSIMP_BUILD_NO_OBJ_EXPORTER",
		"ASSIMP_BUILD_NO_AMF_EXPORTER",
		"ASSIMP_BUILD_NO_HMP_EXPORTER",
		"ASSIMP_BUILD_NO_SMD_EXPORTER",
		"ASSIMP_BUILD_NO_MDC_EXPORTER",
		"ASSIMP_BUILD_NO_MD5_EXPORTER",
		"ASSIMP_BUILD_NO_STL_EXPORTER",
		"ASSIMP_BUILD_NO_LWO_EXPORTER",
		"ASSIMP_BUILD_NO_DXF_EXPORTER",
		"ASSIMP_BUILD_NO_NFF_EXPORTER",
		"ASSIMP_BUILD_NO_RAW_EXPORTER",
		"ASSIMP_BUILD_NO_OFF_EXPORTER",
		"ASSIMP_BUILD_NO_AC_EXPORTER",
		"ASSIMP_BUILD_NO_BVH_EXPORTER",
		"ASSIMP_BUILD_NO_IRRMESH_EXPORTER",
		"ASSIMP_BUILD_NO_IRR_EXPORTER",
		"ASSIMP_BUILD_NO_Q3D_EXPORTER",
		"ASSIMP_BUILD_NO_B3D_EXPORTER",
		-- "ASSIMP_BUILD_NO_COLLADA_EXPORTER",
		"ASSIMP_BUILD_NO_TERRAGEN_EXPORTER",
		"ASSIMP_BUILD_NO_CSM_EXPORTER",
		"ASSIMP_BUILD_NO_3D_EXPORTER",
		"ASSIMP_BUILD_NO_LWS_EXPORTER",
		"ASSIMP_BUILD_NO_OGRE_EXPORTER",
		"ASSIMP_BUILD_NO_OPENGEX_EXPORTER",
		"ASSIMP_BUILD_NO_MS3D_EXPORTER",
		"ASSIMP_BUILD_NO_COB_EXPORTER",
		"ASSIMP_BUILD_NO_BLEND_EXPORTER",
		"ASSIMP_BUILD_NO_Q3BSP_EXPORTER",
		"ASSIMP_BUILD_NO_NDO_EXPORTER",
		"ASSIMP_BUILD_NO_IFC_EXPORTER",
		"ASSIMP_BUILD_NO_XGL_EXPORTER",
		"ASSIMP_BUILD_NO_FBX_EXPORTER",
		"ASSIMP_BUILD_NO_ASSBIN_EXPORTER",
		-- "ASSIMP_BUILD_NO_GLTF_EXPORTER",
		"ASSIMP_BUILD_NO_C4D_EXPORTER",
		"ASSIMP_BUILD_NO_3MF_EXPORTER",
		"ASSIMP_BUILD_NO_X3D_EXPORTER",
		"ASSIMP_BUILD_NO_MMD_EXPORTER",
		"ASSIMP_BUILD_NO_STEP_EXPORTER",
		"ASSIMP_BUILD_NO_SIB_IMPORTER",
	
		-- "ASSIMP_BUILD_NO_MAKELEFTHANDED_PROCESS",
		-- "ASSIMP_BUILD_NO_FLIPUVS_PROCESS",
		-- "ASSIMP_BUILD_NO_FLIPWINDINGORDER_PROCESS",
		-- "ASSIMP_BUILD_NO_CALCTANGENTS_PROCESS",
		"ASSIMP_BUILD_NO_JOINVERTICES_PROCESS",
		-- "ASSIMP_BUILD_NO_TRIANGULATE_PROCESS",
		"ASSIMP_BUILD_NO_GENFACENORMALS_PROCESS",
		-- "ASSIMP_BUILD_NO_GENVERTEXNORMALS_PROCESS",
		"ASSIMP_BUILD_NO_REMOVEVC_PROCESS",
		"ASSIMP_BUILD_NO_SPLITLARGEMESHES_PROCESS",
		"ASSIMP_BUILD_NO_PRETRANSFORMVERTICES_PROCESS",
		"ASSIMP_BUILD_NO_LIMITBONEWEIGHTS_PROCESS",
		-- "ASSIMP_BUILD_NO_VALIDATEDS_PROCESS",
		"ASSIMP_BUILD_NO_IMPROVECACHELOCALITY_PROCESS",
		"ASSIMP_BUILD_NO_FIXINFACINGNORMALS_PROCESS",
		"ASSIMP_BUILD_NO_REMOVE_REDUNDANTMATERIALS_PROCESS",
		"ASSIMP_BUILD_NO_FINDINVALIDDATA_PROCESS",
		"ASSIMP_BUILD_NO_FINDDEGENERATES_PROCESS",
		"ASSIMP_BUILD_NO_SORTBYPTYPE_PROCESS",
		"ASSIMP_BUILD_NO_GENUVCOORDS_PROCESS",
		"ASSIMP_BUILD_NO_TRANSFORMTEXCOORDS_PROCESS",
		"ASSIMP_BUILD_NO_FINDINSTANCES_PROCESS",
		"ASSIMP_BUILD_NO_OPTIMIZEMESHES_PROCESS",
		"ASSIMP_BUILD_NO_OPTIMIZEGRAPH_PROCESS",
		"ASSIMP_BUILD_NO_SPLITBYBONECOUNT_PROCESS",
		"ASSIMP_BUILD_NO_DEBONE_PROCESS",
		"ASSIMP_BUILD_NO_EMBEDTEXTURES_PROCESS",
		"ASSIMP_BUILD_NO_GLOBALSCALE_PROCESS"
    }

    filter "system:windows"
        systemversion "latest"
    
    filter "configurations:Debug"
        runtime "Debug"
        symbols "on"
        defines
        {
           "_DEBUG"
        }

    filter "configurations:Release"
        runtime "Release"
        optimize "on"
        defines
        {
            "_RELEASE"
        }